[project]
name = "orchestra-cli"
version = "0.0.3"
description = "Orchestra CLI. Perform operations with Orchestra locally."
readme = "README.md"
authors = [
    { name = "Orchestra Technologies", email = "support@getorchestra.io" },
]
requires-python = ">=3.8"
dependencies = ["httpx>=0.28.1", "pyyaml>=6.0.2", "typer>=0.16.0"]

[project.scripts]
orchestra-cli = "orchestra_cli.src.cli:app"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
dev = ["pytest>=7.0"]
