[project]
name = "xmcp-server-wxauto"
version = "0.1.3"
description = "自动操作微信MCP服务"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.9.4",
    "wxauto>=39.1.4",
]

[project.scripts]
xmcp-server-wxauto = "xmcp_server_wxauto:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
