[tool.poetry]
name = "a-toad-emo"
version = "0.1.11"
description = "A CLI Tool to generate mobile applications demo video automatically."
authors = ["BlancJH"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
appium-python-client = "^5.0.0"
pyyaml = "^6.0.2"
pytest = "^8.3.5"
mypy = "^1.15.0"

[tool.poetry.group.dev.dependencies]
sphinx-autobuild = "^2024.10.3"
sphinx-rtd-theme = "^3.0.2"
furo = "^2024.8.6"
sphinx = "^8.2.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
a-toad-emo = "a_toad_emo.cli:main"
atdm = "a_toad_emo.cli:main"

