[project]
name = "errormaster"
version = "1.0.0"
description = "errorcatcher"
authors = [
    {name = "howShouldIChosseMyUsername", email = "trademark2179@gmail.com"}
]
readme = "Readme.md"
license = { text = "MIT" }
requires-python = ">=3.7"
dependencies = [
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.setuptools.packages.find]
include = ["errorcatcher"]

[project.urls]
"Homepage" = "https://github.com/yourusername/fnsignal"
"Bug Tracker" = "https://github.com/yourusername/fnsignal/issues" 