[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vman"
dynamic = ["version"]

authors = [
  { name="sivefunc", email="sivefunc@tuta.io" },
]

description = "Video Man Pages"
readme = {file = 'README.md', content-type='text/markdown', charset="UTF-8", variant="GFM"}
requires-python = ">=3.11"

license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]

dependencies = [
]

[project.optional-dependencies]
dev = [
    "pylint"
]

keywords = ['linux', 'python3', 'man']

[tool.setuptools.dynamic]
version = {attr = "vman._version.__version__"}

[project.urls]
Homepage = "https://github.com/Sivefunc/vman"

[project.scripts]
vman = "vman.vman:main"

[tool.setuptools]
py-modules = ['vman']
