[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mcp-connect"
version = "0.1.2"
authors = [
    { name = "MakeyFeng", email = "405426648@qq.com" }
]
description = "Coze-MCP 集成工具，将 Coze 智能体集成到 MCP 平台，实现流式对话功能"
readme = "readme.md"
license = { text = "Your License" }
keywords = ["Coze", "MCP", "integration", "streaming chat"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11"
]
requires-python = ">=3.7"
dependencies = [
    "annotated-types==0.7.0",
    "anyio==4.9.0",
    "authlib==1.6.0",
    "certifi==2025.6.15",
    "cffi==1.17.1",
    "click==8.2.1",
    "colorama==0.4.6",
    "cozepy==0.16.2",
    "cryptography==45.0.4",
    "distro==1.9.0",
    "h11==0.16.0",
    "httpcore==1.0.9",
    "httpx==0.27.2",
    "httpx-sse==0.4.0",
    "idna==3.10",
    "markdown-it-py==3.0.0",
    "mcp==1.9.4",
    "mdurl==0.1.2",
    "pycparser==2.22",
    "pydantic==2.11.7",
    "pydantic-core==2.33.2",
    "pydantic-settings==2.9.1",
    "pygments==2.19.1",
    "python-dotenv==1.1.0",
    "python-multipart==0.0.20",
    "rich==14.0.0",
    "shellingham==1.5.4",
    "sniffio==1.3.1",
    "sse-starlette==2.3.6",
    "starlette==0.47.0",
    "typer==0.16.0",
    "typing-extensions==4.14.0",
    "typing-inspection==0.4.1",
    "uvicorn==0.34.3",
    "websockets==14.2"
]

[project.scripts]
mcp_connect_coze = "mcp_connect_coze.connect_coze:main"

[tool.pytest.ini_options]
addopts = "-v"
testpaths = ["tests"]