[project]
name = "mcp-jira-confluence"
version = "0.1.3"
description = "Model Context Protocol server for Jira and Confluence"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.9.4",
    "httpx>=0.24.0",
    "pydantic>=2.0.0",
]
[[project.authors]]
name = "akhilthomas236"
email = "akhilthomas236@gmail.com"

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project.scripts]
mcp-jira-confluence = "mcp_jira_confluence.server:main"

[tool.hatch.build]
exclude = [
  "/.env",
  "/.pypirc",
  "/.vscode",
  "/.idea",
  "/__pycache__",
  "*.pyc",
  "*.pyo",
  "*.pyd",
  ".Python",
  "*.so",
  ".git",
  ".gitignore",
  ".pytest_cache",
  "tests",
  "test",
  "docs",
  "examples",
]
