[project]
name = "clai-ai"
version = "0.1.6"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.2.1",
    "gitpython>=3.1.44",
    "google-genai>=1.20.0",
    "python-dotenv>=1.1.0",
    "twine>=6.1.0",
    "typer>=0.16.0",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts] 
clay = "cli.main:app"

