[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "avcmt-py"
version = "1.7.0"
description = "avcmt-py: AI-Powered Semantic Release Style Git Commit Automation for Python Project."
authors = [ "Andy Vandaric <andyvandaric@gmail.com>",]
license = "Apache-2.0"
readme = "README.md"
include = [ "avcmt/*",]
[[tool.poetry.packages]]
include = "avcmt"

[tool.ruff]
target-version = "py310"

[tool.poetry.urls]
Homepage = "https://avcmt.avandaric.live"
Repository = "https://github.com/andyvandaric/avcmt-py"
Documentation = "https://avcmt.avandaric.live/docs"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.32"
rich = "^14.0.0"
toml = "^0.10.2"
jinja2 = "^3.1.4"

[tool.poetry.scripts]
avcmt = "avcmt.cli.main:app"
clean = "scripts.clean:main"
format = "scripts.format:main"
lintfix = "scripts.lintfix:main"
check = "scripts.check:main"
setup = "scripts.setup:main"
helper = "scripts.helper:main"
preflight = "scripts.preflight:main"

[tool.ruff.lint]
preview = true
select = [ "E", "F", "I", "N", "UP", "B", "C90", "SIM", "TID", "PL", "PTH", "NPY", "PD", "PERF", "RUF",]
fixable = [ "ALL",]
ignore = [ "D", "ANN", "COM812", "ISC001", "T201", "S603", "S607", "S404", "S701", "B904", "TRY003", "EM102", "E501", "PERF203", "PLR0913", "PLR0917",]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.avcmt.release]
version_path = "pyproject.toml:tool.poetry.version"
changelog_file = "CHANGELOG.md"
branch = "main"
publish_to_pypi = true
repo_url = "https://github.com/andyvandaric/avcmt-py"

[tool.poetry.dependencies.typer]
extras = [ "all",]
version = "^0.12.3"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [ "F401",]

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = [ "avcmt",]

[tool.semantic_release.changelog.default_templates]
changelog_file = "CHANGELOG.md"

[tool.poetry.group.dev.dependencies]
python-dotenv = "^1.0.1"
ruff = "^0.11.13"
pre-commit = "^4.2.0"
python-semantic-release = "^10.1.0"
