[project]
name = "loopypy"
version = "1.0.6"
description = "An official Python wrapper for api.loopy5418.dev"
readme = "README.md"
requires-python = ">=3.7"
license = "MIT"
authors = [
  { name="loopy5418.dev", email="admin@loopy5418.dev" }
]
keywords = ["ai", "wrapper", "loopy", "api"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent"
]
dependencies = [
  "requests",
]

[project.urls]
Homepage = "https://github.com/api-loopy5418-dev/loopypy"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"