[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "syia-mcp-imo-publications-2025-x7k9"
version = "0.1.7"
description = "MCP IMO Publications Module"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.21.0",
    "apscheduler>=3.11.0",
    "aiohttp>=3.11.18",
    "bs4>=0.0.2",
    "cohere>=5.15.0",
    "colorama>=0.4.6",
    "docker>=7.1.0",
    "google-api-python-client>=2.169.0",
    "google-auth-oauthlib>=1.2.2",
    "langchain>=0.3.25",
    "langchain-community>=0.3.24",
    "loguru>=0.7.3",
    "mcp>=1.8.0",
    "motor>=3.7.0",
    "nest-asyncio>=1.6.0",
    "openai>=1.78.1",
    "pandas>=2.2.3",
    "playwright>=1.52.0",
    "pydantic>=2.11.4",
    "pymongo>=4.12.1",
    "rapidfuzz>=3.13.0",
    "tiktoken>=0.9.0",
    "requests>=2.32.3",
    "typesense>=1.0.3",
    "uvicorn>=0.34.2",
    "xmltodict>=0.14.2",
    "boto3",
    "snowflake-connector-python>=3.10.0"
]

[project.urls]
Repository = "https://github.com/syia-ai/mcp-data-science"
Homepage = "https://github.com/syia-ai/mcp-data-science"

[tool.setuptools.packages.find]
include = ["imo_publications*", "utils*", "document_parse*"]
exclude = ["tests*", "logs*", "k8s*", "Agent*", "scheduler*"]

[tool.setuptools.package-data]
"*" = ["config/*"]

[dependency-groups]
dev = [
    "build>=1.2.2.post1",
    "twine>=6.1.0",
]