[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ecdysys"
version = "0.1.2"
description = "Python CLI to update your system packages"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [{ name = "claymorwan", email = "claymorwan@fembois.dev" }]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
]
requires-python = ">=3.13"
dependencies = [
    "build>=1.2.2.post1",
    "colorama==0.4.6",
    "hatchling>=1.27.0",
    "toml==0.10.2",
    "twine>=6.1.0",
]

[project.urls]
Homepage = "https://github.com/claymorwan/ecdysys"
Issues = "https://github.com/claymorwan/ecdysys/issues"

[project.scripts]
ecdysys = "ecdysys.__main__:main"
