[project]
name = "mcp-get-weather-20250618"
version = "0.1.1"
description = "输入OpenWeather-API-KEY，获取天气信息。"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "build>=1.2.2.post1",
    "httpx>=0.28.1",
    "mcp>=1.9.4",
    "twine>=6.1.0",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
