
[build-system]
requires = ["setuptools>=42", "wheel", "build"]
build-backend = "setuptools.build_meta"

[project]
name = "tempo4d"
version = "0.1.2"
description = "A 4D-STEM and diffraction data processing pipeline using PyQt, OpenCV, and Ultralytics"
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT" }

authors = [
  { name = "Arda Genc", email = "ardagenc@ucsb.edu" }
]

dependencies = [
  "numpy",
  "h5py",
  "opencv-python",
  "PyQt5",
  "pyqtgraph",
  "matplotlib",
  "rosettasciio[all]"
]

classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent"
]

[project.urls]
Homepage = "https://github.com/ArdaGen/Neural-Object-Detection-4D-STEM"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests*"]

[tool.setuptools.package-data]
"tempo4d" = ["models/*.pt"]


