[project]
name = "productspy"
version = "0.1.4"
description = "A product price tracker library"
authors = [{ name = "Rayan", email = "you@example.com" }]
dependencies = [
    "requests",
    "beautifulsoup4",
    "playwright"
]
