[tool.poetry]
packages = [{include = "tmyts_utils", from = "src"}]
name = "tmyts-utils"
version = "0.1.5"
description = "Tokenizers for TMYTS' microservices"
authors = ["baosiek <baosiek@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.12"
tokenizers = ">=0.21.1"
dropbox = ">=12.0.2"

[tool.poetry.dev-dependencies]
pytest = "^8.3"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
