[project]
name = "p6plab.azure-pricing-mcp-server"
version = "1.2.0"
description = "A P6P Lab Model Context Protocol (MCP) server for Azure pricing analysis"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.6.0",
    "pydantic>=2.10.6",
    "httpx>=0.25.0",
    "bs4>=0.0.2",
    "pytest>=7.4.0",
    "pytest-asyncio>=0.23.0",
    "typing-extensions>=4.8.0",
]
license = {text = "Apache-2.0"}
license-files = ["LICENSE", "NOTICE"]

authors = [
    {name = "P6P Lab"},
    {name = "P6P Lab MCP", email="peepeepopapapeepeepo+pypi-azure-pricing-mcp-server@gmail.com"},
]
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

[project.scripts]
"p6plab.azure-pricing-mcp-server" = "p6plab.azure_pricing_mcp_server.server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["p6plab"]
