[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "validator-for-postcodes"
version = "0.1.3"
description = "Library for postcodes validation"
authors = [
    { name = "Volodymyr Dubrovskyi", email = "martiniden0@gmail.com" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.7"
dependencies = []

[project.urls]
Repository = "https://github.com/dubrovskyi/validate-postcode"
