[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "yt_dl_cli"
version = "1.0.3"
description = "Video downloader from a number of video streaming services."
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "Oleksandr Kharchenko", email = "kharchenko.oleksandr@icloud.com"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "yt-dlp>=2024.0.0"
]

[project.scripts]
yt-dl-cli = "yt_dl_cli.scripts.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
yt_dl_cli = ["locales/*/LC_MESSAGES/*"]