[project]
name = "mtbs"
version = "0.1.4"
description = "a little lib to interact with Metabase"
readme = "README.md"
authors = [
    { name = "Ruddy", email = "ruddy.at.work@proton.me" }
]
requires-python = ">=3.12.8"
dependencies = [
    "diskcache>=5.6.3",
    "requests==2.31.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
