[project]
name = "add-staves"
version = "0.2.9"
description = "Add empty staves between music systems."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pypdf>=5.6.0",
    "rich>=14.0.0",
    "typer>=0.16.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
[project.scripts]
add-staves = "add_staves.cli:main"

