[project]
name = "hyprpwmenu"
version = "0.2.5"
description = "A modern powermenu for Hyprland."
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "Antrax", email = "fredcox@gmail.com" }]
requires-python = ">=3.13"
dependencies = [
  "confz>=2.1.0",
  "pygobject>=3.52.3",
  "pygobject-stubs>=2.13.0",
  "rich>=14.0.0",
]

[project.urls]
homepage   = "https://github.com/antrax2024/hyprpwmenu"
Repository = "https://github.com/antrax2024/hyprpwmenu"

[project.scripts]
hyprpwmenu = "hyprpwmenu:main"

[build-system]
requires      = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel.sources]
"assets" = "src/hyprpwmenu/assets"
