[project]
name = "ds-uv-test-package"
version = "0.0.1"
description = "testr nuh"
readme = "README.md"
authors = [
    { name = "Dmitry Drozdov", email = "ds.drozdov@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
ds-uv-test-package = "ds_uv_test_package:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
