[tool.poetry]
name = "astroquery_cli"
version = "0.12.9"
description = "CLI for astroquery modules with autocompletion."
authors = ["inoribea <inoribea@outlook.com>"]
readme = "README.md"

packages = [
  { include = "astroquery_cli" }
]

include = [
    { path = "locales/*/LC_MESSAGES/messages.mo", format = "sdist" },
    { path = "locales/*/LC_MESSAGES/messages.mo", format = "wheel" }
]

[tool.poetry.dependencies]
python = ">=3.11"
typer = "^0.15.4"
rich = "^13.5.2"
astropy = "^7.1.0"
babel = "^2.15.0"
requests = "^2.10.0"
astroquery = "^0.4.10"
pyvo = "^1.4.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
snakeviz = "^2.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
aqc = "astroquery_cli.main:cli"
