[project]
name = "xuanxi-bailian-mcp-server"
version = "0.2.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "玄穸_621", email = "2720048423@qq.com" }
]
requires-python = ">=3.10"
dependencies = [
    "bs4>=0.0.2",
    "dashscope>=1.23.5",
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.4",
]

[project.scripts]
xuanxi-bailian-mcp-server = "xuanxi_bailian_mcp_server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
