[tool.poetry]
name = "jsonpath-nz"
version = "1.0.3"
description = "A comprehensive Python library for bidirectional conversion between JSON objects and JSONPath expressions, with advanced features for complex data manipulation, XML processing, JSON merging, and enhanced logging capabilities"
authors = [
    "Yakub Mohammad <yakub@arusatech.com> <arusatechnology@gmail.com>",
    "Rishaad <rishaad@arusatech.com>"
]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/arusatech/jsonpath-nz"
repository = "https://github.com/arusatech/jsonpath-nz"
documentation = "https://github.com/arusatech/jsonpath-nz#readme"
keywords = ["json", "jsonpath", "converter", "dict", "xml", "merge", "logging", "xml2json", "xml_to_json", "parse_jsonpath", "parse_dict", "merge_json", "flatten_dict"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
packages = [
    { include = "jsonpath_nz" }
]

[tool.poetry.dependencies]
python = ">=3.7"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0"
black = "^23.0"
isort = "^5.0"
flake8 = "^6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"