[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ml_lab_shreyy"
version = "1.0.1"
description = "ML Lab Programs as Python Package"
authors = [
    { name = "Shreyas", email = "ishreyasr@gmail.com" }
]
license = { text = "MIT" }
requires-python = ">=3.6"
dependencies = [
    "pandas",
    "scikit-learn",
    "matplotlib",
    "numpy"
]

[project.urls]
"Homepage" = "https://github.com/ishreyasr/ml_lab_shreyy"
