[tool.poetry]
name = "ttyg-evaluation"
version = "2.1.1"
description = "Talk to Your Graph (TTYG) Evaluation is a Python module for evaluating whether LLM agents correctly orchestrate and invoke available tools to answer user questions, based on a gold-standard corpus of tool call expectations."
authors = []
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/Ontotext-AD/ttyg-evaluation"

[tool.poetry.dependencies]
conda-lock = "3.0.1"
python = "3.12.10"
pip = "25.1.1"

[tool.poetry.group.test.dependencies]
pytest = "8.3.5"
pytest-cov = "6.1.1"
jsonlines = "4.0.0"

[tool.poetry.group.test]
optional = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
