[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "productspy"
version = "0.1.5"
description = "A simple Python library to fetch product name and price from popular e-commerce websites."
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
  {name = "Rayan", email = "xrayan.23@gmail.com"}
]
dependencies = [
  "requests>=2.31.0",
  "beautifulsoup4>=4.12.0",
  "urllib3>=1.26.0",
  "playwright>=1.40.0"
]

[project.urls]
"Homepage" = "https://pypi.org/project/productspy/"
"Repository" = "https://github.com/Renqwee/productspy"